---
title: "Formula sheet"
editor: visual
---

## General Part

Mean: $\bar{X} = \frac{\Sigma_{i=1}^nx_i}{N}$

Variance: $S^2_x = \frac{\Sigma_{i=1}^n(x_i-\bar{x})^2}{n-1}$ 

Standardized values (Z-values): $Z = \frac{X-\mu}{\sigma}$ 

Z-statistic in one sample Z-test: $Z = \frac{\bar{x}-\mu}{\sigma_\bar{x}}$

Standard error of the mean: $\sigma_{\bar{x}} = \frac{\sigma}{\sqrt{n}}$

Cohen’s d: $\frac{\bar{X}_1-\bar{X}_2}{s_{pooled}}$

$s^2_{pooled} = \frac{(n_1-1)*s_1^2 + (n_2-1)*s_2^2}{n_1+n_2-2}$

$s_{pooled} = \sqrt{s^2_{pooled}}$

F-statistic in one-way ANOVA: $F (df_b, df_w) = \frac{(SS_b/df_b)}{(SS_w/df_w)} = \frac{MS_b}{(MS_w}$

Simple regression model: $Y' = b_0+b_1X$

Multiple regression model: $Y' = b_0+b_1X_1 + b_2X_2$

Explained variance: $R^2 = \frac{s^2_{y'}}{s^2_y}$

t-statistic in a one sample t-test:
$t = \frac{\bar{X}-\mu_{H0}}{se_x}$, where $se_x = \frac{s_x}{\sqrt{n}}$, $df = n - 1$


t-statistic in an independent samples t-test: 
$t = \frac{(\bar{X}_1-\bar{X}_2)-(\mu_1-\mu_2)_{H0}}{se_{x_1-x_2}}$

$se_{x_1-x_2} = \sqrt{s^2_{pooled}(\frac{1}{n_1}+\frac{1}{n_2})}$


## Business and economics

Logistic function: $P(Y=1|X) = \frac{e^{(b_0 + b_1X)}}{1 + e^{(b_0 + b_1X)}}$

From probability to odds: $\text{odds} = \frac{P}{1 - P}$

From odds to probability: $P = \frac{\text{odds}}{1 + \text{odds}}$

From odds to logit: $\text{logit} = \ln(\text{odds})$

From probability to logit: $\text{logit} = \ln\left(\frac{P}{1 - P}\right)$

From logit to odds: $\text{odds} = e^{\text{logit}}$

From logit to probability: $P = \frac{e^{\text{logit}}}{1 + e^{\text{logit}}}$

Wald test statistic: $W = (\frac{b}{se_b})^2$


## Cognitive neuroscience

Number of Possible Pairwise Comparisons:  $k \times \frac{(k - 1)}{2}$

Factorial ANOVA Linear Model: $Y_{jkl} = \mu_Y + \alpha_k + \beta_l + \alpha\beta_{kl} + \epsilon_{jkl}$

Eta-squared for Factor A: $\eta_A^2 = \frac{SS_A}{SS_{total}}$

Partial eta-squared for Factor A: $\eta_{partial.A}^2 = \frac{SS_A}{SS_A + SS_w}$

Adjusted Mean: $\bar{Y}_{i(adj)} = \bar{Y}_i - b_w(\bar{X}_i - \bar{X})$

t-Statistic in Paired Samples t-Test: $t = \frac{\bar{d}}{\frac{s_{\bar{d}}}{\sqrt{n}}}, \quad \text{df} = n - 1$


## Social Sciences

Reliability: $r_{xx'} = \frac{\text{var}(T)}{\text{var}(X)} = \frac{\text{var}(T)}{\text{var}(T) + \text{var}(E)}$

Eigenvalue of Component 1 for 6 Items: $\lambda_1 = a_{11}^2 + a_{21}^2 + a_{31}^2 + a_{41}^2 + a_{51}^2 + a_{61}^2$

The proportion of Variance Accounted For by component 1 (when there are J items) is: $\text{Proportion VAF} = \frac{\lambda_1}{\text{TotalVar}} = \frac{\lambda_1}{J}$

Component loadings for component 1 and item j are represented as: $a_{j1} = r_{X_jC_1}$

Communality for 2 Components: $h_{j2} = r_{XjC1}^2 + r_{XjC2}^2 = a_{j1}^2 + a_{j2}^2$

Unicity for 2 Components: $b_{j2} = 1 - h_{j2}$
