# Lab 1: Introduction

```{r, include = FALSE}
source("R/booktem_setup.R")
source("R/my_setup.R")
```

## Introduction to Statistics (RECAP)

Today, we will work with a data set on nerdy personality types. For this study, participants completed a survey on how nerdy their personality was and what their general personality was like. Finally, they had to answer some general questions.

Open the data set: Nerdy personality sample.sav Download Nerdy personality sample.sav 

 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
QuestionEdit this question Delete this question
Researchers are interested in the following research question: “An average, do people consider themselves to be nerdy?”

We have to carry out a one sample t-test to answer this question.

Navigate to Analyze à Compare means à One sample T Test
Select the variable Nerdy
Insert the test value 4 (We use 4 as test value because this was the neutral option for the item “I consider myself as nerdy”)
Make sure that the 95% confidence interval is selected
Paste and run the syntax
 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
Question1 ptsEdit this question Delete this question
On the sample level, do people on average consider themselves to be nerdy?
Correct answer
  Yes 
  No 
General answer comments
The sample mean (5.46) is higher than the neutral mid-point of the scale (4; which is also the test value), meaning that, on the sample level, people on average consider themselves to be nerdy.
 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
UnansweredQuestion1 ptsEdit this question Delete this question
The sample mean is higher than the neutral mid-point of the scale, meaning that, in this sample, participants on average consider themselves to be nerdy.

The next thing we would like to test is whether we are allowed to generalize this result to the general population.

We have to carry out a two-tailed t-test using a significance level of 5%.

Write down:

The null hypothesis and alternative hypothesis
The sample results
The t-value and p-value
The conclusion of this test
General answer comments
H0: μ = 4
H1: μ ≠ 4

We have sufficient evidence to believe that, in the population, people on average score higher than the neutral midpoint of the nerdy scale,  = 5.46, t(2520) = 50.933, p < .001.

 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
Question1 ptsEdit this question Delete this question
Now take a look at the 95% confidence interval. As you might recall from the lectures, SPSS does not give us the confidence interval around the sample mean.

What is the lower bound of the confidence interval around the sample mean?

Round your number to two decimal places.


Correct Answers
5.4 (with margin: 0)
 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
Question1 ptsEdit this question Delete this question
What is the correct upper bound?

Again, round your number to two decimal places.

Correct Answers
5.51 (with margin: 0)
 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
Question1 ptsEdit this question Delete this question
Imagine that you would ask for a 99% confidence interval instead of a 95% confidence interval. What do you think happens to the width of the interval?
Correct answer
  The interval becomes wider 
  The interval becomes smaller 
  The interval remains the same 
General answer comments
If we want to be more confident in the correctness of our finding, we will need a wider confidence interval.
 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
Question1 ptsEdit this question Delete this question
Let’s try to verify your answer by rerunning the analysis again but asking for a 99% confidence interval.

Was your answer to the previous question correct?

Correct answer
  Yes 
Correct answer
  No 
 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
UnansweredQuestion1 ptsEdit this question Delete this question
Next, we will run an independent samples t-test to see whether men and women differ in nerdiness.

Navigate to Analyze à Independent-samples T Test
Insert the dependent variable Nerdy
Use Dgen as the grouping variable (this is the dummy variable for gender)
Click on Define groups and enter the values 0 and 1
Go to Options and ensure that you ask for the 95% confidence interval
Paste and run the syntax
 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
UnansweredQuestion1 ptsEdit this question Delete this question
Take a look at the 95% confidence interval. The boundaries are calculated around the mean difference. Explain in your own words what this mean difference entails.
General answer comments
The mean difference in an independent samples t-test is the difference in sample means between the two groups (in this case men and women).

In our sample we see that women score somewhat higher on nerdiness than men. As a result, the mean difference is negative (X difference = −0.026).

 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
UnansweredQuestion1 ptsEdit this question Delete this question
Now, again, we want to know whether we can generalize this result to the population.

Instead of looking at the p-value, however, we now want to use the confidence interval to conclude whether we are allowed to reject the null hypothesis.

To start with, write down the null hypothesis and alternative hypothesis.

(Note: There are two different ways to do this. Check the information button if you are unsure.)

 
We can write the null and alternative hypothesis in two ways.
Either:
H0: μmen = μwoman
H1: μmen ≠ μwoman
Or:
H0: μmen - μwoman = 0
H1: μmen - μwoman ≠ 0

 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
UnansweredQuestion0 ptsEdit this question Delete this question
How can we use the 95% interval to carry out a (two-tailed) significance test?
General answer comments
If we want to do a significance test using the confidence interval, we have the check whether the confidence interval contains the null hypothesis test value.

If it does, there is no significant difference.
If it does not, there is a significant difference.
 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
Question1 ptsEdit this question Delete this question
Can we reject the null hypothesis in this case?
Correct answer
  No 
  Yes 
General answer comments
In this case, the 95% confidence interval contains 0. Hence, we should conclude that there is no significant difference between nerdiness between men and women.


## MRA (RECAP)

Let’s carry on with some multiple regression analysis.

We continue working with the same dataset.

 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
UnansweredQuestion1 ptsEdit this question Delete this question
Researchers want to know whether academic interest can be predicted by several independent variables. They start off with a simple question: “Is there an effect of gender on academic interest?”

Write down the general model and the hypotheses that we want to test.

General answer comments
Additional explanation:

Y’Academic interest = b0 + b1 * Gender

H0: bgender = 0

H1: bgender ≠ 0

 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
QuestionEdit this question Delete this question
Let’s carry out a simple linear regression analysis.

Navigate to Analyze --> Regression --> Linear
Insert Academic_interest as dependent variable and Dgen as independent variable
Go to Statistics and ask for the 95% confidence interval
Paste and run the syntax
 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
Question1 ptsEdit this question Delete this question
Take a look at the 95% confidence interval.

Is there a significant effect of gender on academic interest?

Correct answer
  Yes 
  Np 
General answer comments
The 95% confidence interval does not include 0, so we should conclude that there is a significant effect of gender on academic interest.
 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
Question1 ptsEdit this question Delete this question
What percentage of the variance in academic interest can be explained by gender? Round your answer to one decimal point.
Correct Answers
3.3 (with margin: 0)
 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
QuestionEdit this question Delete this question
Now we will move on with a hierarchical regression analysis. In steps, we will add the variables Gender, Autism, Nerdiness and several personality variables.

Navigate to Analyze --> Regression --> Linear
Keep Academic_interest as DV and Gender as IV. Click on Next.
You arrive at Block 2. Here you can enter the variable you want to add in the second model. Insert the variable Daut. Click on Next.
You arrive at Block 3. Insert the variable Nerdy. Click on Next.
You arrive at Block 4. Insert the variables TIPI1, TIPI2, TIPI5, and TIPI8.
Go to Statistics. Ask for R square change.
Paste and run the syntax.
 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
Question1 ptsEdit this question Delete this question
Based on the model comparison tests, which model should we interpret?
Correct answer
  Model 4 
  Model 1 
  Model 2 
  Model 3 
General answer comments
Every subsequent model explains significantly more variance than the previous model. Hence, Model 4 is the best model (explaining the most variance with the least number of variables possible).

Hence, based on the model comparison test, we should interpret Model 4.

 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
Question1 ptsEdit this question Delete this question
How much variance does Model 3 explain on top of what is already explained by Model 2? Write down your answer in percentages and round to one decimal point.
Correct Answers
21.6 (with margin: 0.1)
 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
UnansweredQuestion1 ptsEdit this question Delete this question
Take a look at the change statistics.

Why is df1 of model 3 equal to 1? And why is df1 of model 4 equal to 4?

General answer comments
From Model 2 to Model 3 we included 1 additional variable, resulting in df = 1.

From Model 3 to Model 4 we included 4 additional variables, resulting in df = 4.

 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
Question1 ptsEdit this question Delete this question
Take a look at the regression coefficients of Model 4 in the table Coefficients.

What is the estimated regression coefficient of the variable Nerdy?
Round your answer to three decimal points.

Correct Answers
1.423 (with margin: 0.005)
 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
UnansweredQuestion1 ptsEdit this question Delete this question
Write down as precise as possible, the correct interpretation of this estimated regression coefficient.
General answer comments
With every unit increase in the variable Nerdy, the predicted score for Academic interest increases with 1.423.
 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
Question1 ptsEdit this question Delete this question
Take a look at the confidence intervals of the estimated coefficients.

Which variables do not have a significant effect on academic interest controlled for the other variables in the model?

  Critical, quarrelsome 
Correct answer
  Disorganized, careless 
Correct answer
  Open to new experience, complex 
  Autism 
  Extraverted, enthusiastic 
  Gender 
  Nerdy 
  
  
## Confidence Intervals

In this assignment we will work on some questions regarding the confidence interval. We focus on the confidence interval around the mean, but everything you learn can also be applied to confidence intervals around the mean difference or regression coefficients.

Finish the following sentence. The confidence interval around the mean is constructed around the…

Correct answer
  Sample mean 
  Population mean (under H0) 
General answer comments
The confidence interval around the mean is constructed around the sample mean.

Usually, we don’t even know the true population mean!

 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
Question1 ptsEdit this question Delete this question
In the population the variable IQ is normally distributed with μ=100 and σ=15.

Imagine that we drew 2000 samples from the population. For each of the samples we would calculate a 90% confidence interval around the sample mean. If you had to make a guess, how many intervals would you expect to contain the value 100?

Correct Answers
1,800 (with margin: 0)
General answer comments
We would expect that for 90% of the 2000 samples the confidence interval would contain 100. Hence, we expect this for 1800 samples.
 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
Question1 ptsEdit this question Delete this question
Imagine we drew a sample from the population and we calculated the 95% confidence interval around the sample mean for a particular variable. The lower bound of the confidence interval is equal to 85 and the upper bound to 95.

Which of the following statements is correct?

Correct answer
  There is a 95% chance that if we would draw a new sample for the same population in the future, the calculated confidence interval for that future sample contains the true population value. 
  There is a 95% chance that if we would draw a new sample for the same population in the future, the true population value lies between 85 and 95. 
  The probability that the population mean lies between 85 and 95 is 95%. 
  There is a 95% chance that the population mean lies between 85 and 95. 
 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
QuestionEdit this question Delete this question
Confidence intervals can be best interpreted in the context of many samples. IF we would draw a huge number of samples from the population, we expect that for 95% of the samples the confidence interval will contain the population mean. However, based on one confidence interval (e.g., one with lower bound 85 and upper bound 95), we can NEVER draw the conclusion that the there is a 95% chance that the population mean lies between 85 and 95. Whether the population mean lies within the interval is not a matter of probability: the population mean either lies within the boundaries of the confidence interval, or it does not. We just don’t know whether that’s the case because we typically do not know the value of the population mean. Also, by chance, our estimated confidence interval might be very far away from μ. We just don’t know….

The interpretation of the confidence interval is not very straightforward. Yet we can study the properties of the confidence interval with this nice shiny app. Open the app in a new tab or window (Link to WebbAppLinks to an external site.).

 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
Question1 ptsEdit this question Delete this question
Click on the tab Confidence interval for a Mean.
For Select shape of population distribution, choose Bell-shaped
Keep the mean on 50 and the standard deviation on 10
Keep the confidence level at 95%
With this shiny app we can draw samples from a population for a variable with μ=50 and σ=10. It is nice to know the population mean μ (which we normally do not). Now we can draw a sample, and we can actually check whether μ lies within the boundaries of the confidence interval.

Draw one sample with N=20.

Does μ lie within the boundaries of the confidence interval?

Correct answer
  Yes 
Correct answer
  No 
General answer comments
Findings are likely to be different each time you let the program take a sample for you.

Since we chose a CI of 95%, 95% of these samples should have the population mean in the interval, whereas for 5% of these samples it should not.
 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
UnansweredQuestion1 ptsEdit this question Delete this question
If we would draw 20 samples, for how many samples would you expect the confidence interval to contain the value 50?

Now draw 19 more samples so you end up with 20 samples. Is your expectation confirmed? Why (not)?

General answer comments
The program shows you the percentage of confidence intervals that contain μ. When we draw a huge number of samples, 95% of the intervals should contain μ. However, if we draw a limited number of samples, the percentage could differ a little from 95%.
 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
UnansweredQuestion1 ptsEdit this question Delete this question
Reset the program and draw 1000 samples. Does 95% of the calculated confidence intervals contain μ? If not, draw another 1000 samples. Did anything change? Keep on drawing an extra 1000 samples until 95% of the confidence intervals contain μ. How many samples did you need?
 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
UnansweredQuestion1 ptsEdit this question Delete this question
Reset the program and draw 10 new samples.

What do you expect to happen to the confidence intervals if we would draw smaller samples (and everything else remains the same)? First think for yourself what will happen. Then verify your answer by drawing 10 samples with N=5.

Now, draw 10 samples with N=100.

Explain why the intervals change.

General answer comments
By increasing the sample size, our estimate becomes more precise. This will lead to more narrow confidence intervals.

Mathematically it also makes sense, because the confidence interval is based on the standard error. Remember that the formula for the standard error is σ = σ/N. A smaller sample size leads to a smaller standard error, which leads to a narrower interval.

Note that this does not mean that less or more confidence intervals will contain μ. In the long run this is still 95%.
 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
UnansweredQuestion1 ptsEdit this question Delete this question
Change the sample size back to 20. Draw 10 samples.

Now change the standard deviation to 12 instead of 10. Again draw 10 samples.

What change do you observe?

General answer comments
If the standard deviation increases (and everything else stays the same) the confidence interval will become wider.
 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
UnansweredQuestion1 ptsEdit this question Delete this question
Put the standard deviation back to 10. Draw 100 samples.

Change the level of confidence to 90% and draw another 100 samples.

What happens? You should at least notice two differences.

General answer comments
If we move from a 95% confidence interval to a 90% confidence interval (and everything else stays the same) we see that:

The intervals become narrower
Less intervals contain μ(approximately 90%)
