# Lab 1: Introduction

```{r, include = FALSE}
source("R/booktem_setup.R")
source("R/my_setup.R")
```

## Norm Violating Behaviors

In this assignment we are going to take a look at scale that measures whether people engage in norm violating behaviors.

The scale consists of the following items:

Joyriding
Taking soft drugs
Accepting a bribe
Throwing away litter
Driving under influence of alcohol
Smoking in public places
Speeding over limit
Euthanasia
Open the datafile evs.sav Download evs.sav.

 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
QuestionEdit this question Delete this question
In SPSS, navigate to Analyze --> Scale --> Reliability Analysis.

Select the seven items that are in this scale.

Then go to statistics and select the options “Item”, “Scale” and “Scale if item deleted”. Click on continue.

Now paste and run the syntax.

 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
Question1 ptsEdit this question Delete this question
What is the value of Cronbach’s Alpha? (round your answer to three decimal places)
Correct Answers
0.693 (with margin: 0.005)
 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
Question1 ptsEdit this question Delete this question
Finish the following sentence.

This Cronbach’s Alpha is…

Correct answer
  Doubtful 
  Adequate 
  Good 
  Poor 
 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
UnansweredQuestion1 ptsEdit this question Delete this question
The Cronbach’s Alpha gives an estimate of the scale reliability.

Describe in your own words what scale reliability entails.

General answer comments
The reliability of a scale shows the internal consistency of the answers on all items on a scale.
 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
UnansweredQuestion1 ptsEdit this question Delete this question
Look at the “Item-Total Statistics” table.

What does the last column “Cronbach’s alpha if Item Deleted” tell you?

General answer comments
The values in the column “Cronbach’s Alpha if item deleted” shows the Cronbach’s Alpha of the scale if one of the items would be deleted. In other words, it shows what the impact on the reliability of the scale would be if a certain item would be excluded from the scale.
 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
Question1 ptsEdit this question Delete this question
If you would have to give advice to a researcher concerning this scale, would you tell him/her to leave items out of this scale? With which item would you start?
Correct answer
  Euthenasia 
  Speeding over limit 
  Smoking in public places 
  Driving under influence of alcohol 
  Throwing away litter 
  Accepting a bribe 
  Taking soft drugs 
  Joyriding 
General answer comments
We usually consider excluding an item from a scale if the Cronbach’s Alpha would increase if the item were to be excluded.

Given the Cronbach’s Alpha of our original scale (.693), the table shows the only deleting the item “Euthenasia” would result in a higher Cronbach’s Alpha.

Hence, based on this SPSS-output, we should advice the researcher to leave out the item “Euthenasia” of this scale.

 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
QuestionEdit this question Delete this question
You finished this assignment!

Please check your answers and the additional explanation for each step before preceding to the next assignment.

## Machiavellianism

In this assignment we will look into the latent concept Machiavellianism.

Nicollo Machiavelli was an Italian diplomat, politician, writer, and poet (amongst many other things). He is most famous for his book Il Principe in which he describes and encourages immoral behavior in politics, because “the ends justify the means”.

Nowadays, psychologists use the term Machiavellianism to describe a personality type that is centered on deceitfulness and cynicism – and, hence, an absence of morality and empathy. This term is sometimes coined in personality, forensic, and social psychology. For more information on Machiavellianism, see WikipediaLinks to an external site..

Open the datafile shortmach2.sav Download shortmach2.sav. The data file contains data on Machiavellianism and some other variables.

 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
Question1 ptsEdit this question Delete this question
The included Machiavellianism scale consists of the following 20 items. These items are scored on a 1-5 Likert scale ranging from "Disagree" to "Agree".

Q1. Never tell anyone the real reason you did something unless it is useful to do so.

Q2. The best way to handle people is to tell them what they want to hear.

Q3. One should take action only when sure it is morally right.

Q4. Most people are basically good and kind.

Q5. It is safest to assume that all people have a vicious streak, and it will come out when they are given a chance.

Q6. Honesty is the best policy in all cases.

Q7. There is no excuse for lying to someone else.

Q8. Generally speaking, people won't work hard unless they're forced to do so.

Q9. All in all, it is better to be humble and honest than to be important and dishonest.

Q10. When you ask someone to do something for you, it is best to give the real reasons for wanting it rather than giving reasons which carry more weight.

Q11. Most people who get ahead in the world lead clean, moral lives.

Q12. Anyone who completely trusts anyone else is asking for trouble.

Q13. The biggest difference between most criminals and other people is that the criminals are stupid enough to get caught.

Q14. Most people are brave.

Q15. It is wise to flatter important people.

Q16. It is possible to be good in all respects.

Q17. P.T. Barnum was wrong when he said that there's a sucker born every minute.

Q18. It is hard to get ahead without cutting corners here and there.

Q19. People suffering from incurable diseases should have the choice of being put painlessly to death.

Q20. Most people forget more easily the death of their parents than the loss of their property.

 

Items can be indicative or contra-indicative of a certain trait.

Which items are contra-indicative to the trait Machiavellianism?

 

Consult the information button for more information on some of the items.

  Q1 
  Q2 
Correct answer
  Q3 
Correct answer
  Q4 
  Q5 
Correct answer
  Q6 
Correct answer
  Q7 
  Q8 
Correct answer
  Q9 
Correct answer
  Q10 
Correct answer
  Q11 
  Q12 
  Q13 
Correct answer
  Q14 
  Q15 
Correct answer
  Q16 
Correct answer
  Q17 
  Q18 
  Q19 
  Q20 
 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
QuestionEdit this question Delete this question
If an item is contra indicative, low scores on these items indicate a lot of Machiavellianist traits, whereas high scores indicate not so much of an endorsement of Machiavellianist traits in one’s personality.

In this assignment, the following questions are contra-indicative:
Q3, Q4, Q6, Q7, Q9, Q10, Q11, Q14, Q16, and Q17.

We need to recode contra indicative items before we carry out reliability analysis.

However, just to see what happens, let’s first carry out a reliability analysis with all original (i.e. not recoded) variables.

Take the following steps:

Analyze --> Scale --> Reliability Analysis
Select the 20 items (Q1A - Q20A)
Click on Statistics
Under Descriptives, select Items, Scale, and Scale if item deleted
Under Inter-Item, select Correlations
Paste and run the syntax
 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
UnansweredQuestion1 ptsEdit this question Delete this question
Inspect Cronbach’s alpha. Do you think that the scale is reliable (in its current state)? Why (not)?
General answer comments
The Cronbach’s Alpha is .233.

Following the rules of thumb for evaluating the Cronbach’s Alpha we’ve seen in the lectures, we can conclude that the Cronbach’s Alpha is very low, indicating low reliability of the scale.

 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
QuestionEdit this question Delete this question
As you’ve probably noticed, Cronbach’s alpha is very low. So, at first glance, it seems that the Machiavellianism scale is not very reliable.

However, this low reliability is a result of the fact that we have not recoded our contra-indicative items yet. We can also see this in the inter-item correlation table; many of the items are negatively correlated! Let’s rectify this.

We have to recode all contra indicative items, but let’s start with recoding item Q3A. We can use either Recode into different variables or Compute to recode contra indicative items. In this example we will use the latter.

Navigate to Transform --> Compute Variable
Give a new name to the recoded item in the box Target Variable, such as Q3r
In the box Numeric Expression, enter 6 - Q3A
Paste the syntax
Use the information button to verify whether you generated the correct syntax.

 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
UnansweredQuestion0 ptsEdit this question Delete this question
With the syntax from the previous step, we only recode item Q3. However, we want to recode Q4, Q6, Q7, Q9, Q10, Q11, Q14, Q16, and Q17 as well.

Copy the syntax that you obtained in the previous step. Adjust the syntax by hand in such a way that you will now recode variable Q4 (Hint: you only need to make two adjustments). Use the information button to verify whether you wrote the correct syntax.

Then, repeat this step for the other eight variables that need to be recoded.

If you’re done doing so, select all syntax and run it.

For the second person in the dataset, write down the score on the original variable Q3A AND the recoded variable Q3r. Compare the two values. Based on this comparison, do you think you successfully recoded the variable?

General answer comments
On the contra-indicative item (Q4A), the score of the participant in row 2 should be 4.
On the recoded version of this variable (Q4r), the score of the participant in row 2 should be 2.
 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
QuestionEdit this question Delete this question
We will now run the reliability analysis including the recoded items.

Take the following steps:

Navigate to Analyze --> Scale --> Reliability Analysis.
Select the 20 items. For the indicative items you should select the original items (e.g., Q1A, Q2A) and for the contra-indicative items the recoded items (e.g., Q3r, Q4r).
Click on Statistics.
Under Descriptives, select Items, Scale, Scale if item deleted.
Under Inter-Item, select Correlations.
Paste and run the syntax.
 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
UnansweredQuestion1 ptsEdit this question Delete this question
What can you conclude about the reliability of the scale? Is there any reason to worry? Mention the guidelines from the lecture in your answer.
General answer comments
The Cronbach’s Alpha is now .887 (whereas it used to be .233 before recoding the items).

We can conclude that this Cronbach’s Alpha is good, suggesting good reliability of this scale.

 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
Question1 ptsEdit this question Delete this question
Check the corrected item total correlations.

Which items of the following list has the smallest association with other items in the scale?

Correct answer
  Q19 
  Q1 
  Q11 
  Q17 
 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
UnansweredQuestion1 ptsEdit this question Delete this question
Do you think it makes sense that this item is correlated the least with the rest of the scale? Substantiate your answer.
General answer comments
This item-total correlation of Q19 is .255.

Item Q19 reads: “People suffering from incurable diseases should have the choice of being put painlessly to death”.

One could argue that a high score on this item should relate to a low score on the scale for agreeing with this item nowadays might actually show empathy with those suffering.

 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
Question1 ptsEdit this question Delete this question
Inspect Cronbach’s alpha if item deleted. If you had to remove one item based on this Cronbach’s alpha if item deleted, which item would it be?
Correct answer
  Q17 
  Q19 
  Q11 
  Q1 
General answer comments
Based on the Cronbach’s Alpha if item deleted, we would delete the item that would result in the greatest increase in Cronbach’s Alpha if it would be deleted.

We find the highest Cronbach’s Alpha if item deleted for the item Q17r (.889).

Therefore, based on the Cronbach’s Alpha if item deleted, we would delete item Q17r.

 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
UnansweredQuestion1 ptsEdit this question Delete this question
Taking everything into consideration, would you remove any items from the Machiavellianism scale?
General answer comments
Taking the statistical output into consideration, we might want to consider removing item Q17r or item Q19.

We do so for two reasons:
1) They both correlate less than .3 with the other items on the scale, and
2) have a Cronbach’s Alpha if item deleted higher than .887 (the current Cronbach’s Alpha of the scale).

Please note that we should always take into consideration theoretical reasons as well when deciding to delete an item from a scale. In this assignment, however, we base our conclusions on statistical reasons only.

 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
QuestionEdit this question Delete this question
You might want to consider removing item Q17 or Q19. They both correlate less than .3 with the rest of the scale, and have an Alpha if item removed higher than .887.

We always remove items one by one. We start with the worst item. After removing a bad item from a scale, the item-statistics will change a little. It might be that the item-statistics improve, and that there is no need to remove the second item.

However, since the differences are not that big and the scale reliability is pretty high, we will keep both items in our scale for the remainder of this assignment.

 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
QuestionEdit this question Delete this question
Once we finished reliability analysis, we can use the scale in other analyses.

In order to do that, we need to arrive at a total scale score. So, we need one score for each person in the dataset that tells what their score is on the personality trait Machiavellianism.

There are several methods of obtaining such a total score, but one straightforward and easy way is to calculate the sum score.

Navigate to Transform à Compute Variable.
Give a new name to the sum score in the box Target Variable, such as Mach.
In the box Numeric Expression, enter all variables and add together (i.e., Q1A + Q2A + Q3r …. + Q20A). Ensure that you use the recoded variables for the contra-indicative items!
Paste and run the syntax.
 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
Question1 ptsEdit this question Delete this question
We will now use our newly developed scale in a regression analysis! In this analysis we will try to explain Machiavellianism based on the variables Gender (0=men; 1=women), Age and Voted (0=Voted in past election, 1= Not voted in past election).

Navigate to Analyze --> Regression --> Linear
Enter the sumscore Mach as dependent variable
Enter Gender, Age, and Voted as independent variables
Paste and run the syntax
Inspect the Model Summary table. How much of the variance in Machiavellianism do the variables Gender, Age and Voted explain? Round your number to three decimal points.

Correct Answers
0.126 (with margin: 0.005)
 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
Question1 ptsEdit this question Delete this question
Do Gender, Age and Voting together explain a significant amount of variance in the variable Machiavellianism? (Use a significance level of 5%)
Correct answer
  Yes 
  No 
General answer comments
The ANOVA table displays the results of the F-test that tests whether the R2 is significant.

Using a significance level of α=.05, we should conclude that a significant proportion of variance in the variable Mach is explained by the variable Gender, Age, and Voted, F(3, 3587)=172.07, p<.001.

 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
Question1 ptsEdit this question Delete this question
Inspect the table Coefficients and take a look at the partial effects. Which of the variables has a significant partial effect on Machiavellianism (use a significance level of 5%)?
Correct answer
  Gender 
Correct answer
  Age 
  Voting 
General answer comments
The t-tests in the Coefficients table show that Gender (p<.001) and Age (p<.001) on Mach are significant predictors of March, controlled for Voted.

Controlled for Gender and Age, the effect of Voted on March is not significant (p=.686).

 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
Question1 ptsEdit this question Delete this question
Controlled for Age and Voting, which group (men or women) scores higher on the Machiavellianism scale?
Correct answer
  Men 
  Women 
General answer comments
Given that in the variable Gender men are coded as 0 and women are coded as 1, and that the regressions coefficient for Gender is negative (-7.440), we should conclude that men score higher on Machiavellianism than women, controlled for Age and Voting.
 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
Question1 ptsEdit this question Delete this question
Finish the following sentence.

Controlled for Gender and Voting, if we would increase one year in age, the predicted score on the Machiavellianism scale would ________________________ .

Correct answer
  Decrease with 0.294 units. 
  Increase with 0.294 units. 
  Increase with 0.243 units. 
  Decrease with 0.243 units. 
  
  
## Solidarity

Welcome to the third assignment.

In this assignment, you will evaluate the reliability of a scale measuring solidarity.

Download and open the following data file: solidarity.sav Download solidarity.sav to get started.

 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
QuestionEdit this question Delete this question
You’ve practiced with reliability analysis in the previous assignments. Now you can use that knowledge to evaluate the reliability of the solidarity scale more independently.

Run a reliability analysis by navigating to Analyze à Scale à Reliability Analysis. Include all eleven items that are part of the scale (v266 to v276). Don’t forget to enable the required statistics in the Statistics menu! Paste and run the syntax.

Use the information button to verify whether you generated the correct syntax.

 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
Question1 ptsEdit this question Delete this question
Inspect the output of the reliability analysis.

Do you have to recode questions?

  Yes 
Correct answer
  No 
General answer comments
We check if we should recode any items by looking at how they are phrased. To do so, we don’t necessarily need to look at the output.

We could, however, also use the inter-item correlations displayed in the output to check if we should recode items. If any of the inter-item correlations are negative, this should be in indication for contra-indicative items.

An unexpectedly low Cronbach’s Alpha could also indicate contra-indicative items that should be recoded before proceeding.

 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
Question1 ptsEdit this question Delete this question
Now you can evaluate the reliability of the scale.

Which items, of any, do not contribute positively to the reliability of the scale?

Correct answer
  Q79A 
Correct answer
  Q80E 
  Q79B 
  Q79C 
  Q79D 
  Q79E 
  Q79F 
  Q80A 
  Q80B 
  Q80C 
  Q80D 
General answer comments
The Cronbach’s Alpha for this scale is .847.

The Cronbach’s Alpha if item deleted for the items Q79A (.849) and Q80E (.866) are higher than the current Cronbach’s Alpha of the scale. This indicates that these items negatively contribute to the reliability of the scale.

 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
Question1 ptsEdit this question Delete this question
One item should probably be removed from the scale.

Which one?

  Q79A 
  Q79B 
  Q79C 
  Q79D 
  Q79E 
  Q79F 
  Q80A 
  Q80B 
  Q80C 
  Q80D 
Correct answer
  Q80E 
 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
UnansweredQuestion1 ptsEdit this question Delete this question
For several reasons, we could consider removing item Q80E from the scale.

What would be the reasons for removing item Q80E from the scale?

General answer comments
Deleting item Q80E from the scale results in a higher increase in Cronbach’s Alpha than deleting item Q79A. This a statistical reason to delete item Q80E from the scale instead of item Q79A.

Moreover, comparing the content of item Q80E to the content of the other questions in the scale, we can conclude that the content of this item is off-topic. This is a theoretical reason for excluding item Q80E from the scale.

 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
Question1 ptsEdit this question Delete this question
Which item is most typical for the scale?
  Q79A 
  Q79B 
  Q79C 
Correct answer
  Q79D 
  Q79E 
  Q79F 
  Q80A 
  Q80B 
  Q80C 
  Q80D 
  Q80E 
General answer comments
We can tell from the higher item-total correlation, that tells us that this item has the strongest correlation with all other variables on the scale.

Also, the reliability of the scale would decrease most if this item would be deleted from the scale.

 
Move To...This element is a more accessible alternative to drag & drop reordering. Press Enter or Space to move this question.
Question1 ptsEdit this question Delete this question
Last, construct sum scores on the scale for all individuals (via Transform à Compute). Make sure you do not include item Q80E!

Once you created the sum score, have SPSS show the mean for this total score.

What is the mean value of the sum score? (round to 3 decimal places).

Correct Answers
27.897 (with margin: 0.005)
